#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prob.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prob.y"

#include<stdio.h>
#include<string.h>
extern FILE *yyin;
extern char buffer[];
char err[1000];
int e=0;
int label=0;
char* genvar();
char imcode[10000][10000];
int code=0;

struct Node{
	struct Node* next;
	int addr;
};
struct Expr{
	char str[1000];
	int lv;
};
struct BoolNode{
	struct Node* T;
	struct Node* F;
	struct Node* N;
};

struct Node* createNode(int addr){
	struct Node* node = (struct Node*)malloc(sizeof(struct Node));
	node->next = NULL;
	node->addr = addr;
	return node;
}

struct Expr* createExpr(){
	return (struct Expr*)malloc(sizeof(struct Expr));
}

struct BoolNode* createBoolNode(){
	struct BoolNode* node = (struct BoolNode*)malloc(sizeof(struct BoolNode));
	return node;
}

struct Node* merge(struct Node* a,struct Node* b){
	if (a==NULL && b==NULL) return NULL;
	if (a==NULL) return b;
	if (b==NULL) return a;
	struct Node* t = a;
	while(t->next!=NULL){
		t = t->next; 
	}
	t->next = b;
	return a;
}
void backpatch(struct Node* a,int addr){
	while(a!=NULL){
		// printf("%d\n",a->addr);
		if (imcode[a->addr][strlen(imcode[a->addr])-1]!='\n')sprintf(imcode[a->addr]+strlen(imcode[a->addr]),"%d\n",addr);
		a = a->next;
	}
}	

#line 63 "prob.y"
typedef union{
	char str[1000];
	struct BoolNode* b;
	struct Expr *expr;
	int addr;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parse_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	PASN	258
#define	MASN	259
#define	DASN	260
#define	SASN	261
#define	OR	262
#define	AND	263
#define	LT	264
#define	GT	265
#define	LE	266
#define	GE	267
#define	EQ	268
#define	NE	269
#define	INC	270
#define	DEC	271
#define	UMINUS	272
#define	ELSE	273
#define	IDEN	274
#define	NUM	275
#define	IF	276
#define	TR	277
#define	FL	278
#define	WHILE	279
#define	EOF	280


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int PASN;
static const int MASN;
static const int DASN;
static const int SASN;
static const int OR;
static const int AND;
static const int LT;
static const int GT;
static const int LE;
static const int GE;
static const int EQ;
static const int NE;
static const int INC;
static const int DEC;
static const int UMINUS;
static const int ELSE;
static const int IDEN;
static const int NUM;
static const int IF;
static const int TR;
static const int FL;
static const int WHILE;
static const int EOF;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,PASN=258
	,MASN=259
	,DASN=260
	,SASN=261
	,OR=262
	,AND=263
	,LT=264
	,GT=265
	,LE=266
	,GE=267
	,EQ=268
	,NE=269
	,INC=270
	,DEC=271
	,UMINUS=272
	,ELSE=273
	,IDEN=274
	,NUM=275
	,IF=276
	,TR=277
	,FL=278
	,WHILE=279
	,EOF=280


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::PASN=258;
const int YY_parse_CLASS::MASN=259;
const int YY_parse_CLASS::DASN=260;
const int YY_parse_CLASS::SASN=261;
const int YY_parse_CLASS::OR=262;
const int YY_parse_CLASS::AND=263;
const int YY_parse_CLASS::LT=264;
const int YY_parse_CLASS::GT=265;
const int YY_parse_CLASS::LE=266;
const int YY_parse_CLASS::GE=267;
const int YY_parse_CLASS::EQ=268;
const int YY_parse_CLASS::NE=269;
const int YY_parse_CLASS::INC=270;
const int YY_parse_CLASS::DEC=271;
const int YY_parse_CLASS::UMINUS=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::IDEN=274;
const int YY_parse_CLASS::NUM=275;
const int YY_parse_CLASS::IF=276;
const int YY_parse_CLASS::TR=277;
const int YY_parse_CLASS::FL=278;
const int YY_parse_CLASS::WHILE=279;
const int YY_parse_CLASS::EOF=280;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		105
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 280 ? yytranslate[x] : 52)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    19,     2,     2,    22,
    23,    18,    15,     2,    16,     2,    17,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    27,     2,
    36,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    34,     2,    35,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    20,
    21,    24,    25,    26,    28,    29,    30,    31,    32,    33
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,    13,    24,    27,    35,    39,    42,    45,
    49,    52,    55,    57,    59,    61,    63,    65,    70,    75,
    79,    83,    87,    91,    95,    99,   101,   103,   104,   105,
   109,   113,   117,   121,   125,   129,   133,   137,   141,   143,
   145,   147,   149,   151,   153,   158,   163,   167,   171,   175,
   179,   183,   187,   189,   191,   193,   195,   197,   198,   200,
   202,   203,   205
};

static const short yyrhs[] = {    39,
    42,     0,    44,    27,     0,    29,    22,    41,    23,    42,
    38,     0,    29,    22,    41,    23,    42,    38,    25,    43,
    42,    38,     0,    29,     1,     0,    32,    42,    22,    41,
    23,    42,    38,     0,    34,    39,    35,     0,    45,    27,
     0,    45,     1,     0,    39,    42,    38,     0,    38,    42,
     0,    39,     1,     0,    36,     0,     3,     0,     4,     0,
     5,     0,     6,     0,    41,     7,    42,    41,     0,    41,
     8,    42,    41,     0,    45,     9,    45,     0,    45,    10,
    45,     0,    45,    13,    45,     0,    45,    14,    45,     0,
    45,    11,    45,     0,    45,    12,    45,     0,    30,     0,
    31,     0,     0,     0,    45,    40,    45,     0,    45,    15,
    45,     0,    45,    16,    45,     0,    45,    18,    45,     0,
    45,    17,    45,     0,    45,    19,    45,     0,    22,    45,
    23,     0,    22,    45,     1,     0,    45,    46,    27,     0,
    47,     0,    15,     0,    16,     0,    18,     0,    17,     0,
    19,     0,    51,    48,    26,    49,     0,    51,    26,    48,
    49,     0,    51,    28,    50,     0,    51,    26,    50,     0,
    51,    20,    28,     0,    51,    21,    28,     0,    51,    28,
    20,     0,    51,    28,    21,     0,    20,     0,    21,     0,
    48,     0,    26,     0,    28,     0,     0,    26,     0,    28,
     0,     0,    16,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    88,   101,   102,   106,   112,   113,   121,   125,   126,   128,
   131,   133,   137,   138,   139,   140,   141,   143,   149,   154,
   162,   168,   174,   180,   186,   192,   199,   206,   207,   213,
   224,   225,   226,   227,   228,   229,   230,   231,   232,   234,
   234,   234,   234,   234,   235,   252,   269,   278,   285,   286,
   287,   288,   290,   290,   292,   293,   294,   295,   296,   297,
   298,   299,   299
};

static const char * const yytname[] = {   "$","error","$illegal.","PASN","MASN",
"DASN","SASN","OR","AND","LT","GT","LE","GE","EQ","NE","'+'","'-'","'/'","'*'",
"'%'","INC","DEC","'('","')'","UMINUS","ELSE","IDEN","';'","NUM","IF","TR","FL",
"WHILE","EOF","'{'","'}'","'='","S","A","STMNTS","ASSGN","BOOLEXPR","M","NN",
"ASNEXPR","EXPR","OP","TERM","OPR","B","C","UN",""
};
#endif

static const short yyr1[] = {     0,
    37,    38,    38,    38,    38,    38,    38,    38,    38,    39,
    39,    39,    40,    40,    40,    40,    40,    41,    41,    41,
    41,    41,    41,    41,    41,    41,    41,    42,    43,    44,
    45,    45,    45,    45,    45,    45,    45,    45,    45,    46,
    46,    46,    46,    46,    47,    47,    47,    47,    47,    47,
    47,    47,    48,    48,    49,    49,    49,    49,    50,    50,
    50,    51,    51
};

static const short yyr2[] = {     0,
     2,     2,     6,    10,     2,     7,     3,     2,     2,     3,
     2,     2,     1,     1,     1,     1,     1,     4,     4,     3,
     3,     3,     3,     3,     3,     1,     1,     0,     0,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     1,     1,
     1,     1,     1,     1,     4,     4,     3,     3,     3,     3,
     3,     3,     1,     1,     1,     1,     1,     0,     1,     1,
     0,     1,     0
};

static const short yydefact[] = {    63,
    62,    63,     0,    28,    63,    28,     0,     0,     0,    39,
     0,     0,     5,    63,     0,     0,    11,    12,    63,     2,
     9,    14,    15,    16,    17,    63,    63,    63,    63,    63,
     8,    13,    63,     0,    53,    54,    61,    61,     0,    37,
    36,    26,    27,     0,     0,    63,     7,    63,    10,    31,
    32,    34,    33,    35,    30,    38,    49,    50,    53,    54,
    59,    60,    58,    48,    51,    52,    47,    58,    28,    28,
    28,    63,    63,    63,    63,    63,    63,     0,    56,    57,
    55,    46,    45,    63,    63,    63,    20,    21,    24,    25,
    22,    23,    28,    18,    19,     3,    63,    29,     6,    28,
    63,     4,     0,     0,     0
};

static const short yydefgoto[] = {   103,
     6,     7,    33,    44,    15,   100,     8,     9,    34,    10,
    81,    82,    64,    11
};

static const short yypact[] = {   109,
-32768,    84,     3,-32768,   109,-32768,    70,   -22,    33,-32768,
   143,   117,-32768,    -9,    -3,    87,-32768,-32768,    95,-32768,
-32768,-32768,-32768,-32768,-32768,    -4,    31,    39,    40,   123,
-32768,-32768,    84,   -10,     7,    29,   146,   155,    28,-32768,
-32768,-32768,-32768,     1,   142,    -9,-32768,   109,-32768,    26,
    26,-32768,-32768,-32768,    64,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   158,-32768,-32768,-32768,-32768,   158,-32768,-32768,
-32768,    84,    84,    84,    84,    84,    84,     8,-32768,-32768,
-32768,-32768,-32768,    -9,    -9,   109,    64,    64,    64,    64,
    64,    64,-32768,    12,-32768,    34,   109,-32768,-32768,-32768,
   109,-32768,    68,    97,-32768
};

static const short yypgoto[] = {-32768,
    -8,    96,-32768,   -43,    -6,-32768,-32768,     0,-32768,-32768,
    -5,    37,    72,-32768
};


#define	YYLAST		186


static const short yytable[] = {    17,
    19,    12,    78,    13,    20,    39,     1,    69,    70,    48,
    49,     1,     2,    45,    69,    70,    56,     2,    46,    70,
    42,    43,   -40,    71,    14,    50,    51,    52,    53,    54,
    93,    63,    55,    21,    57,    22,    23,    24,    25,    49,
    94,    95,    28,    29,    30,    45,     1,    26,    27,    28,
    29,    30,     2,    68,     1,     1,    58,   -41,    98,    31,
     2,     2,    84,    85,    86,   -43,   -42,   104,    32,   -28,
    18,    87,    88,    89,    90,    91,    92,    96,    26,    27,
    28,    29,    30,    45,    45,   -28,    97,    18,    99,   -28,
   -28,   -28,   102,   101,    -1,   -28,   105,   -28,   -28,     1,
    16,   -28,   -28,   -28,    83,     2,   -28,   -28,   -28,    67,
     1,     0,   -28,     0,   -28,   -28,     2,    40,   -28,     0,
   -28,    47,     0,     3,     1,     0,     4,     0,     5,     0,
     2,    26,    27,    28,    29,    30,     0,     3,     1,    41,
     4,     0,     5,     0,     2,     0,     0,     0,     0,   -44,
    72,    73,    74,    75,    76,    77,    26,    27,    28,    29,
    30,     0,    35,    36,     0,    59,    60,     0,    37,     0,
    38,    61,     0,    62,    65,    66,     0,    59,    60,     0,
    61,     0,    62,    79,     0,    80
};

static const short yycheck[] = {     6,
     7,     2,    46,     1,    27,    11,    16,     7,     8,    16,
    19,    16,    22,    14,     7,     8,    27,    22,    22,     8,
    30,    31,    27,    23,    22,    26,    27,    28,    29,    30,
    23,    37,    33,     1,    28,     3,     4,     5,     6,    48,
    84,    85,    17,    18,    19,    46,    16,    15,    16,    17,
    18,    19,    22,    26,    16,    16,    28,    27,    25,    27,
    22,    22,    69,    70,    71,    27,    27,     0,    36,     0,
     1,    72,    73,    74,    75,    76,    77,    86,    15,    16,
    17,    18,    19,    84,    85,    16,    93,     1,    97,    20,
    21,    22,   101,   100,     0,    26,     0,    28,    29,    16,
     5,    32,    16,    34,    68,    22,    20,    21,    22,    38,
    16,    -1,    26,    -1,    28,    29,    22,     1,    32,    -1,
    34,    35,    -1,    29,    16,    -1,    32,    -1,    34,    -1,
    22,    15,    16,    17,    18,    19,    -1,    29,    16,    23,
    32,    -1,    34,    -1,    22,    -1,    -1,    -1,    -1,    27,
     9,    10,    11,    12,    13,    14,    15,    16,    17,    18,
    19,    -1,    20,    21,    -1,    20,    21,    -1,    26,    -1,
    28,    26,    -1,    28,    20,    21,    -1,    20,    21,    -1,
    26,    -1,    28,    26,    -1,    28
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 88 "prob.y"
{
	if (e){
			printf("%s\nRejected -> %s -> Could not generate Three Address Code\n",buffer,err);
			e=0;err[0]="\0";buffer[0]='\0';} 
 		else {	
			backpatch(yyvsp[-1].b->N,yyvsp[0].addr); // for last statement
			printf("%s\nAccepted -> Three Address Code:\n",buffer);
			for (int i=0;i<code;i++){
				printf("%s",imcode[i]);
			}
			
		};
    break;}
case 2:
#line 101 "prob.y"
{if (!e){yyval.b = yyvsp[-1].b;};
    break;}
case 3:
#line 102 "prob.y"
{if (!e){backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
										yyval.b = createBoolNode();
										yyval.b->N = merge(yyvsp[-3].b->F,yyvsp[0].b->N);
										};
    break;}
case 4:
#line 106 "prob.y"
{if (!e){
		backpatch(yyvsp[-7].b->T,yyvsp[-5].addr);
		backpatch(yyvsp[-7].b->F,yyvsp[-1].addr);
		yyval.b = createBoolNode();
		yyval.b->N = merge(merge(yyvsp[-4].b->N,yyvsp[-2].b->N),yyvsp[0].b);
	};
    break;}
case 5:
#line 112 "prob.y"
{if (!e){strcpy(err,"missing (");yyerrok;e=1;};
    break;}
case 6:
#line 113 "prob.y"
{if (!e){
		backpatch(yyvsp[0].b->N,yyvsp[-5].addr);
		backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
		yyval.b = createBoolNode();
		yyval.b->N = yyvsp[-3].b->F;
		sprintf(imcode[code],"%d goto %d\n",code,yyvsp[-5].addr);
		code++;
		};
    break;}
case 7:
#line 121 "prob.y"
{if (!e) {
						yyval.b = createBoolNode();
						yyval.b->N = yyvsp[-1].b->N;
						};
    break;}
case 8:
#line 125 "prob.y"
{;;
    break;}
case 9:
#line 126 "prob.y"
{if (!e) {strcpy(err,"; missing");yyerrok;e=1;};
    break;}
case 10:
#line 128 "prob.y"
{if (!e){backpatch(yyvsp[-2].b->N,yyvsp[-1].addr);
					yyval.b = createBoolNode();
					yyval.b->N = yyvsp[0].b->N;};
    break;}
case 11:
#line 131 "prob.y"
{if (!e){yyval.b = createBoolNode();
		yyval.b->N = yyvsp[-1].b->N;};
    break;}
case 12:
#line 133 "prob.y"
{if (!e){ // To skip random statements and not crash
		e=1;strcpy(err,"Invalid Statement");
	};
    break;}
case 13:
#line 137 "prob.y"
{strcpy(yyval.str,"=");;
    break;}
case 14:
#line 138 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 15:
#line 139 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 16:
#line 140 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 17:
#line 141 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 18:
#line 144 "prob.y"
{  backpatch(yyvsp[-3].b->F,yyvsp[-1].addr);
							 	yyval.b = createBoolNode();	
								yyval.b->T = merge(yyvsp[-3].b->T,yyvsp[0].b->T);
								yyval.b->F = yyvsp[0].b->F;
							 ;
    break;}
case 19:
#line 149 "prob.y"
{	backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
								yyval.b = createBoolNode();
								yyval.b->T = yyvsp[0].b->T;
								yyval.b->F = merge(yyvsp[-3].b->F,yyvsp[0].b->F);
								;
    break;}
case 20:
#line 154 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);
							code++;
							};
    break;}
case 21:
#line 162 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 22:
#line 168 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 23:
#line 174 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 24:
#line 180 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 25:
#line 186 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 26:
#line 192 "prob.y"
{if (!e){
		yyval.b = createBoolNode();
		yyval.b->T = createNode(code);
		sprintf(imcode[code],"%d goto ",code);
		code++;
	};
    break;}
case 27:
#line 199 "prob.y"
{if (!e){
		yyval.b = createBoolNode();
		yyval.b->F = createNode(code);
		sprintf(imcode[code],"%d goto ",code);
		code++;
	};
    break;}
case 28:
#line 206 "prob.y"
{yyval.addr=code;;
    break;}
case 29:
#line 207 "prob.y"
{yyval.b=createBoolNode();
	yyval.b->N = createNode(code);
	sprintf(imcode[code],"%d goto ",code);
	code++;
	;
    break;}
case 30:
#line 213 "prob.y"
{if (!e && yyvsp[-2].expr->lv){if (strlen(yyvsp[-1].str)==1){sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].expr,yyvsp[0].expr);code++;}
							else{
								char* t = genvar();
								sprintf(imcode[code],"%d %s = %s %c %s\n",code,t,yyvsp[-2].expr,yyvsp[-1].str[0],yyvsp[0].expr);code++;
								sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].expr,t);code++;
								
							}
							yyval.b = createBoolNode();
							}
							if (!yyvsp[-2].expr->lv){e=1;strcpy(err,"L value not assignable");};
    break;}
case 31:
#line 224 "prob.y"
{if (!e){char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s + %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 32:
#line 225 "prob.y"
{if (!e){char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s - %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 33:
#line 226 "prob.y"
{if (!e){char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s * %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 34:
#line 227 "prob.y"
{if (!e){char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s / %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 35:
#line 228 "prob.y"
{if (!e){char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s % %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 36:
#line 229 "prob.y"
{if (!e){strcpy(yyval.expr->str,yyvsp[-1].expr->str);};
    break;}
case 37:
#line 230 "prob.y"
{e=1;strcpy(err,"missing R-Paren");yyerrok;;
    break;}
case 38:
#line 231 "prob.y"
{e=1;strcpy(err,"Missing operand");yyerrok;;
    break;}
case 39:
#line 232 "prob.y"
{yyval.expr = createExpr();strcpy(yyval.expr->str,yyvsp[0].expr);yyval.expr->lv=yyvsp[0].expr->lv;;
    break;}
case 45:
#line 235 "prob.y"
{if (strcmp(yyvsp[-3].str,"-")){
							char*t2=genvar();
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t2,yyvsp[-1].str,yyvsp[-2].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-1].str,t2);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t2);} 
					  else {
							if (!strcmp(yyvsp[-2].str,"--")){e=1;strcpy(err,"--- not allowed");}
							else{
								char*t=genvar();char*t2=genvar();
								sprintf(imcode[code],"%s = %s %c 1\n%s = %s\n%s = - %s\n",t,yyvsp[-1].str,yyvsp[-2].str[0],yyvsp[-1].str,t,t2,t);
								yyval.expr = createExpr();
								strcpy(yyval.expr->str,t2);	
								}
							}
						yyval.expr->lv = 1;
					 ;
    break;}
case 46:
#line 252 "prob.y"
{if (strcmp(yyvsp[-3].str,"-")){char*t = genvar();char*t2=genvar();
							sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-2].str);code++;
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t2,yyvsp[-2].str,yyvsp[-1].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].str,t2);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t);
							} 
					 	else{
							char* t = genvar();char* t1 = genvar();char *t3 = genvar();
							sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-2].str);code++;
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t1,yyvsp[-2].str,yyvsp[-1].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].str,t1);code++;
							sprintf(imcode[code],"%d %s = -%s\n",code,t3,t);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t3);	
						  	}
							yyval.expr->lv=0;;
    break;}
case 47:
#line 269 "prob.y"
{if (!strcmp(yyvsp[-2].str,"-")) {char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);
										sprintf(imcode[code],"%d %s = - %s\n",code,t,yyvsp[-1].str);
										code++;} 
				else{char* t = genvar();yyval.expr = createExpr();
					yyval.expr = createExpr();
					strcpy(yyval.expr->str,t);
					sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-1].str);code++;
				}
				yyval.expr->lv = 0;;
    break;}
case 48:
#line 278 "prob.y"
{if (!strcmp(yyvsp[-2].str,"-")) {char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);
										sprintf(imcode[code],"%d %s = - %s\n",code,t,yyvsp[-1].str);
										code++;} 
				 else{char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr,t);
				 		sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-1].str);
						code++;}
				yyval.expr->lv = 1;;
    break;}
case 49:
#line 285 "prob.y"
{e=1;strcpy(err,"cannot increment a constant value");;
    break;}
case 50:
#line 286 "prob.y"
{e=1;strcpy(err,"cannot decrement a constant value");;
    break;}
case 51:
#line 287 "prob.y"
{e=1;strcpy(err,"cannot increment a constant value");;
    break;}
case 52:
#line 288 "prob.y"
{e=1;strcpy(err,"cannot decrement a constant value");;
    break;}
case 53:
#line 290 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 54:
#line 290 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 55:
#line 292 "prob.y"
{e=1;strcpy(err,"expression is not assignable");;
    break;}
case 56:
#line 293 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 57:
#line 294 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 59:
#line 296 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 60:
#line 297 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 62:
#line 299 "prob.y"
{strcpy(yyval.str,"-");;
    break;}
case 63:
#line 299 "prob.y"
{strcpy(yyval.str,"");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 301 "prob.y"


void findfloat(char* t){
	int ans=0;
	while(t!='\0') if (t++=='.') ans=1;
	return ans;
}

char* genvar(){
	char *re = (char*)malloc(sizeof(char)*100);
    sprintf(re,"t%d",label);
    label++;
    return re;
}

int yyerror(char* msg){
	/* printf("%s",msg); */
	return 0;
}

int main(int argc,char* argv[]){
	/* yydebug=1; */
	yyin = fopen(argv[1],"r");
	yyparse();
	return 0;
}


