#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prob.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prob.y"

#include<stdio.h>
#include<string.h>
extern FILE *yyin;
extern char buffer[];
char err[1000];
int e=0;
int label=0;
char* genvar();
char imcode[10000][10000];
int code=0;
int offset=0;
int saveoffset;

typedef struct Symbol{
	char name[100];
	char type[100];
	int size;
	int offset;
	struct Symbol*next;
} Symbol;

struct Type{
	char str[1000];
	int size;
};

struct Decl{
	char key[1000];
	char type[1000];
	int size;
	int re;
	struct Decl* next;
};

struct Node{
	struct Node* next;
	int addr;
};
struct Expr{
	char str[1000];
	char type[100];
	int lv;
};
struct BoolNode{
	struct Node* T;
	struct Node* F;
	struct Node* N;
};

struct Node* createNode(int addr){
	struct Node* node = (struct Node*)malloc(sizeof(struct Node));
	node->next = NULL;
	node->addr = addr;
	return node;
}

struct Decl* createDecl(char* key){
	struct Decl *node = (struct Decl*)malloc(sizeof(struct Decl));
	node->re=0;
	strcpy(node->key,key);
	return node; 
}

struct Expr* createExpr(){
	return (struct Expr*)malloc(sizeof(struct Expr));
}

struct Type* createType(){
	return (struct Type*)malloc(sizeof(struct Type));
}

struct BoolNode* createBoolNode(){
	struct BoolNode* node = (struct BoolNode*)malloc(sizeof(struct BoolNode));
	return node;
}

struct Node* merge(struct Node* a,struct Node* b){
	if (a==NULL && b==NULL) return NULL;
	if (a==NULL) return b;
	if (b==NULL) return a;
	struct Node* t = a;
	while(t->next!=NULL){
		t = t->next; 
	}
	t->next = b;
	return a;
}

int checkfloat(char* t){
	while(*t){
		if (*t=='.') return 1;
		t++;
	}
	return 0;
}

void backpatch(struct Node* a,int addr){
	while(a!=NULL){
		// printf("%d\n",a->addr);
		if (imcode[a->addr][strlen(imcode[a->addr])-1]!='\n')sprintf(imcode[a->addr]+strlen(imcode[a->addr]),"%d\n",addr);
		a = a->next;
	}
}	

Symbol* createSymbol(char* name){
	Symbol* node = (Symbol*)malloc(sizeof(Symbol));
	strcpy(node->name,name);
	return node;
}

typedef struct Env {
    struct Env* prev;
	int prev_offset;
    struct Table* table;
} Env;

Env* envs[1000]; 
int env_count = 0;  

typedef struct TableEntry {
    char* key;
    Symbol* value;
    struct TableEntry* next;
} TableEntry;

typedef struct Table {
    TableEntry** buckets;
    int size;
} Table;

#define TABLE_SIZE 501

unsigned int hash(const char* key) {
    unsigned int hash = 0;
    while (*key) {
        hash = (hash << 5) + *key++;
    }
    return hash % TABLE_SIZE;
}

Table* create_table() {
    Table* table = malloc(sizeof(Table));
    table->buckets = calloc(TABLE_SIZE, sizeof(TableEntry*));
    table->size = TABLE_SIZE;
    return table;
}

void put(Table* table, const char* key, Symbol* sym) {
    unsigned int index = hash(key);
    TableEntry* new_entry = malloc(sizeof(TableEntry));
    new_entry->key = strdup(key);
    new_entry->value = sym;
    new_entry->next = table->buckets[index];
    table->buckets[index] = new_entry;
}

Symbol* get(Table* table, const char* key) {
    unsigned int index = hash(key);
    TableEntry* entry = table->buckets[index];
    while (entry) {
        if (strcmp(entry->key, key) == 0) {
            return entry->value;
        }
        entry = entry->next;
    }
    return NULL;
}

Env* create_env(Env* prev,int offset) {
    Env* env = malloc(sizeof(Env));
    env->prev = prev;
    env->table = create_table();
	env->prev_offset = offset;
	envs[env_count++] = env;
    return env;
}

void env_put(Env* env, const char* key, Symbol* sym) {
    put(env->table, key, sym);
}

Symbol* env_get(Env* env, const char* key) {
    for (Env* e = env; e != NULL; e = e->prev) {
        Symbol* found = get(e->table, key);
        if (found != NULL) {
            return found;
        }
    }
    return NULL;
}

Env* top = NULL;
void print_table(Table* table) {
    for (int i = 0; i < table->size; i++) {
        TableEntry* entry = table->buckets[i];
        while (entry) {
            printf("0x%04X %s %s \n",entry->value->offset,entry->value->name,entry->value->type);
            entry = entry->next;
        }
    }
}

void print_all_envs() {
	printf("\nStorage Layout");
    for (int i = 0; i < env_count; i++) {
        printf("\n\n", i);
        print_table(envs[i]->table);
    }
}

void checkType(struct Expr* op1,struct Expr* op2,char* opr1,char*opr2,char* type){
	if (strcmp(op1->type,op2->type)==0){
		strcpy(type,op1->type);
		return;
	}
	if (strcmp(op1->type,"int")==0 && strcmp(op2->type,"float")==0){
		char* t = genvar();
		strcpy(opr1,t);
		sprintf(imcode[code],"%d %s = (float) %s\n",code,opr1,op1->str);
		code++;
		strcpy(type,"float");
		return;
	}
	if (strcmp(op1->type,"float")==0 && strcmp(op2->type,"int")==0){
		char* t = genvar();
		strcpy(opr2,t);
		sprintf(imcode[code],"%d %s = (float) %s\n",code,opr2,op2->str);
		code++;
		strcpy(type,"float");
		return;
	}
}
void checkTypeAssign(struct Expr* op1,struct Expr* op2,char*opr ){
	if (strcmp(op1->type,op2->type)==0){
		return;
	}
	if (strcmp(op1->type,"int")==0 && strcmp(op2->type,"float")==0){
		char* t = genvar();
		strcpy(opr,t);
		sprintf(imcode[code],"%d %s = (int) %s\n",code,opr,op2->str);
		code++;
		return;
	}
	if (strcmp(op1->type,"float")==0 && strcmp(op2->type,"int")==0){
		char* t = genvar();
		strcpy(opr,t);
		sprintf(imcode[code],"%d %s = (float) %s\n",code,opr,op2->str);
		code++;
		return;
	}
}


#line 256 "prob.y"
typedef union{
	char str[1000];
	struct BoolNode* b;
	struct Expr *expr;
	int addr;
	struct Type* type;
	struct Decl* decl;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_parse_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	PASN	258
#define	MASN	259
#define	DASN	260
#define	SASN	261
#define	OR	262
#define	AND	263
#define	LT	264
#define	GT	265
#define	LE	266
#define	GE	267
#define	EQ	268
#define	NE	269
#define	INC	270
#define	DEC	271
#define	UMINUS	272
#define	ELSE	273
#define	IDEN	274
#define	NUM	275
#define	IF	276
#define	TR	277
#define	FL	278
#define	WHILE	279
#define	INT	280
#define	FLOAT	281
#define	CHAR	282
#define	EOF	283


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int PASN;
static const int MASN;
static const int DASN;
static const int SASN;
static const int OR;
static const int AND;
static const int LT;
static const int GT;
static const int LE;
static const int GE;
static const int EQ;
static const int NE;
static const int INC;
static const int DEC;
static const int UMINUS;
static const int ELSE;
static const int IDEN;
static const int NUM;
static const int IF;
static const int TR;
static const int FL;
static const int WHILE;
static const int INT;
static const int FLOAT;
static const int CHAR;
static const int EOF;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,PASN=258
	,MASN=259
	,DASN=260
	,SASN=261
	,OR=262
	,AND=263
	,LT=264
	,GT=265
	,LE=266
	,GE=267
	,EQ=268
	,NE=269
	,INC=270
	,DEC=271
	,UMINUS=272
	,ELSE=273
	,IDEN=274
	,NUM=275
	,IF=276
	,TR=277
	,FL=278
	,WHILE=279
	,INT=280
	,FLOAT=281
	,CHAR=282
	,EOF=283


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::PASN=258;
const int YY_parse_CLASS::MASN=259;
const int YY_parse_CLASS::DASN=260;
const int YY_parse_CLASS::SASN=261;
const int YY_parse_CLASS::OR=262;
const int YY_parse_CLASS::AND=263;
const int YY_parse_CLASS::LT=264;
const int YY_parse_CLASS::GT=265;
const int YY_parse_CLASS::LE=266;
const int YY_parse_CLASS::GE=267;
const int YY_parse_CLASS::EQ=268;
const int YY_parse_CLASS::NE=269;
const int YY_parse_CLASS::INC=270;
const int YY_parse_CLASS::DEC=271;
const int YY_parse_CLASS::UMINUS=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::IDEN=274;
const int YY_parse_CLASS::NUM=275;
const int YY_parse_CLASS::IF=276;
const int YY_parse_CLASS::TR=277;
const int YY_parse_CLASS::FL=278;
const int YY_parse_CLASS::WHILE=279;
const int YY_parse_CLASS::INT=280;
const int YY_parse_CLASS::FLOAT=281;
const int YY_parse_CLASS::CHAR=282;
const int YY_parse_CLASS::EOF=283;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		137
#define	YYFLAG		-32768
#define	YYNTBASE	44

#define YYTRANSLATE(x) ((unsigned)(x) <= 283 ? yytranslate[x] : 65)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     9,     2,     2,     2,    20,     2,     2,    23,
    24,    19,    16,    40,    17,     2,    18,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    28,     2,
    41,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    42,     2,    43,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    38,     2,    39,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,    10,    11,    12,    13,    14,    15,    21,
    22,    25,    26,    27,    29,    30,    31,    32,    33,    34,
    35,    36,    37
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     6,     8,    11,    14,    21,    32,    36,    44,
    45,    50,    53,    56,    60,    62,    66,    70,    75,    77,
    81,    84,    88,    93,    95,    97,    99,   103,   106,   108,
   110,   112,   114,   116,   121,   126,   129,   133,   137,   141,
   145,   149,   153,   157,   159,   161,   162,   163,   167,   171,
   175,   179,   183,   187,   191,   195,   197,   199,   201,   203,
   205,   207,   212,   217,   221,   225,   229,   233,   237,   241,
   243,   245,   247,   249,   251,   252,   254,   256,   257,   259
};

static const short yyrhs[] = {    -1,
    45,    52,    55,    37,     0,    37,     0,     1,    37,     0,
    57,    28,     0,    30,    23,    54,    24,    55,    46,     0,
    30,    23,    54,    24,    55,    46,    26,    56,    55,    46,
     0,    30,     1,    37,     0,    33,    55,    23,    54,    24,
    55,    46,     0,     0,    38,    47,    52,    39,     0,    38,
    39,     0,    58,    28,     0,    58,     1,    37,     0,    48,
     0,    51,    49,    28,     0,    27,    40,    49,     0,    27,
    50,    40,    49,     0,    27,     0,    27,    41,    58,     0,
    27,    50,     0,    42,    29,    43,     0,    42,    29,    43,
    50,     0,    34,     0,    35,     0,    36,     0,    52,    55,
    46,     0,    46,    55,     0,    41,     0,     3,     0,     4,
     0,     5,     0,     6,     0,    54,     7,    55,    54,     0,
    54,     8,    55,    54,     0,     9,    54,     0,    23,    54,
    24,     0,    58,    10,    58,     0,    58,    11,    58,     0,
    58,    14,    58,     0,    58,    15,    58,     0,    58,    12,
    58,     0,    58,    13,    58,     0,    31,     0,    32,     0,
     0,     0,    58,    53,    58,     0,    58,    16,    58,     0,
    58,    17,    58,     0,    58,    19,    58,     0,    58,    18,
    58,     0,    58,    20,    58,     0,    23,    58,    24,     0,
    58,    59,    28,     0,    60,     0,    16,     0,    17,     0,
    19,     0,    18,     0,    20,     0,    64,    61,    27,    62,
     0,    64,    27,    61,    62,     0,    64,    29,    63,     0,
    64,    27,    63,     0,    64,    21,    29,     0,    64,    22,
    29,     0,    64,    29,    21,     0,    64,    29,    22,     0,
    21,     0,    22,     0,    61,     0,    27,     0,    29,     0,
     0,    27,     0,    29,     0,     0,    17,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   287,   287,   300,   301,   307,   308,   312,   319,   324,   332,
   332,   339,   340,   341,   345,   347,   378,   390,   405,   415,
   426,   439,   443,   447,   448,   449,   451,   454,   458,   459,
   460,   461,   462,   464,   470,   475,   482,   489,   497,   503,
   509,   515,   521,   527,   534,   541,   542,   548,   565,   566,
   567,   568,   569,   570,   572,   573,   575,   575,   575,   575,
   575,   576,   623,   670,   685,   705,   706,   707,   708,   710,
   710,   712,   713,   714,   715,   716,   717,   718,   719,   719
};

static const char * const yytname[] = {   "$","error","$illegal.","PASN","MASN",
"DASN","SASN","OR","AND","'!'","LT","GT","LE","GE","EQ","NE","'+'","'-'","'/'",
"'*'","'%'","INC","DEC","'('","')'","UMINUS","ELSE","IDEN","';'","NUM","IF",
"TR","FL","WHILE","INT","FLOAT","CHAR","EOF","'{'","'}'","','","'='","'['","']'",
"S","@1","A","@2","DECLSTATEMENT","DECLLIST","INDEX","TYPE","STMNTS","ASSGN",
"BOOLEXPR","M","NN","ASNEXPR","EXPR","OP","TERM","OPR","B","C","UN",""
};
#endif

static const short yyr1[] = {     0,
    45,    44,    44,    44,    46,    46,    46,    46,    46,    47,
    46,    46,    46,    46,    46,    48,    49,    49,    49,    49,
    49,    50,    50,    51,    51,    51,    52,    52,    53,    53,
    53,    53,    53,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    55,    56,    57,    58,    58,
    58,    58,    58,    58,    58,    58,    59,    59,    59,    59,
    59,    60,    60,    60,    60,    60,    60,    60,    60,    61,
    61,    62,    62,    62,    62,    63,    63,    63,    64,    64
};

static const short yyr2[] = {     0,
     0,     4,     1,     2,     2,     6,    10,     3,     7,     0,
     4,     2,     2,     3,     1,     3,     3,     4,     1,     3,
     2,     3,     4,     1,     1,     1,     3,     2,     1,     1,
     1,     1,     1,     4,     4,     2,     3,     3,     3,     3,
     3,     3,     3,     1,     1,     0,     0,     3,     3,     3,
     3,     3,     3,     3,     3,     1,     1,     1,     1,     1,
     1,     4,     4,     3,     3,     3,     3,     3,     3,     1,
     1,     1,     1,     1,     0,     1,     1,     0,     1,     0
};

static const short yydefact[] = {     0,
     0,     3,    80,     4,    79,    80,     0,    46,    24,    25,
    26,    10,    46,    15,     0,    46,     0,     0,    56,     0,
     0,     0,    80,     0,    12,    80,    28,    19,     0,    80,
     5,     0,    30,    31,    32,    33,    80,    80,    80,    80,
    80,    13,    29,    80,     0,    70,    71,    78,    78,     0,
    54,     8,    80,    80,    44,    45,     0,     0,    80,    46,
     0,    80,     0,    21,    16,     2,    27,    14,    49,    50,
    52,    51,    53,    48,    55,    66,    67,    70,    71,    76,
    77,    75,    65,    68,    69,    64,    75,    36,     0,     0,
    46,    46,    46,    80,    80,    80,    80,    80,    80,     0,
    11,    80,    17,    20,     0,     0,    73,    74,    72,    63,
    62,    37,    80,    80,    80,    38,    39,    42,    43,    40,
    41,    46,    22,    18,    34,    35,     6,    80,    23,    47,
     9,    46,    80,     7,     0,     0,     0
};

static const short yydefgoto[] = {   135,
     3,    13,    26,    14,    29,    64,    15,    16,    44,    57,
    24,   132,    17,    18,    45,    19,   109,   110,    83,    20
};

static const short yypact[] = {    99,
   -22,-32768,   130,-32768,-32768,   -10,     1,-32768,-32768,-32768,
-32768,   -19,-32768,-32768,    -5,-32768,    -3,    13,-32768,   175,
   132,   -14,    39,    11,-32768,   130,-32768,    49,    15,   108,
-32768,     8,-32768,-32768,-32768,-32768,    44,    46,    59,    60,
    85,-32768,-32768,   -10,    18,    21,    26,   178,   187,    22,
-32768,-32768,    39,    39,-32768,-32768,     2,   174,    39,    25,
    -5,   -10,    52,    28,-32768,-32768,-32768,-32768,    87,    87,
-32768,-32768,-32768,   204,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   190,-32768,-32768,-32768,-32768,   190,-32768,    20,   159,
-32768,-32768,-32768,   -10,   -10,   -10,   -10,   -10,   -10,    51,
-32768,   130,-32768,   204,    41,    -5,-32768,-32768,-32768,-32768,
-32768,-32768,    39,    39,   130,   204,   204,   204,   204,   204,
   204,-32768,    43,-32768,    90,-32768,    75,   130,-32768,-32768,
-32768,-32768,   130,-32768,   103,   110,-32768
};

static const short yypgoto[] = {-32768,
-32768,   -29,-32768,-32768,   -53,    -9,-32768,    89,-32768,   -48,
   -13,-32768,-32768,    -2,-32768,-32768,    -8,    30,    69,-32768
};


#define	YYLAST		224


static const short yytable[] = {    27,
    67,    22,    30,    21,    88,    89,     5,   103,    91,    92,
   100,    50,     6,    32,     4,    33,    34,    35,    36,    25,
    58,    28,    52,    23,    31,    93,    91,    92,    37,    38,
    39,    40,    41,    59,    69,    70,    71,    72,    73,    82,
    42,    74,    65,   112,    68,    75,   102,    53,    87,    76,
    58,    90,   124,    43,    77,     5,    58,    91,    92,   104,
     5,    54,     5,   101,   125,   126,     6,   106,     6,    55,
    56,   -57,    67,   -58,   122,     5,     5,   113,   114,   115,
   105,     6,     6,   123,    63,   127,   -60,   -59,    61,    62,
    63,   116,   117,   118,   119,   120,   121,    92,   131,     1,
   130,     5,   136,   134,    39,    40,    41,     6,   128,   137,
    58,    58,   -61,   129,    60,    -1,   111,    86,   133,    -1,
    -1,    -1,     0,     0,     5,    -1,     0,    -1,    -1,     0,
     6,    -1,    -1,    -1,    -1,     2,    -1,     7,     0,     0,
     8,     9,    10,    11,    66,    12,     5,    37,    38,    39,
    40,    41,     6,     0,     0,    51,     0,     0,     0,     7,
     0,     0,     8,     9,    10,    11,     0,    12,    94,    95,
    96,    97,    98,    99,    37,    38,    39,    40,    41,     0,
     0,     0,    51,    94,    95,    96,    97,    98,    99,    37,
    38,    39,    40,    41,     0,    46,    47,     0,    78,    79,
     0,    48,     0,    49,    80,     0,    81,    84,    85,     0,
    78,    79,     0,    80,     0,    81,   107,     0,   108,    37,
    38,    39,    40,    41
};

static const short yycheck[] = {    13,
    30,     1,    16,     6,    53,    54,    17,    61,     7,     8,
    59,    20,    23,     1,    37,     3,     4,     5,     6,    39,
    23,    27,    37,    23,    28,    24,     7,     8,    16,    17,
    18,    19,    20,    23,    37,    38,    39,    40,    41,    48,
    28,    44,    28,    24,    37,    28,    60,     9,    27,    29,
    53,    54,   106,    41,    29,    17,    59,     7,     8,    62,
    17,    23,    17,    39,   113,   114,    23,    40,    23,    31,
    32,    28,   102,    28,    24,    17,    17,    91,    92,    93,
    29,    23,    23,    43,    42,   115,    28,    28,    40,    41,
    42,    94,    95,    96,    97,    98,    99,     8,   128,     1,
    26,    17,     0,   133,    18,    19,    20,    23,   122,     0,
   113,   114,    28,   123,    26,    17,    87,    49,   132,    21,
    22,    23,    -1,    -1,    17,    27,    -1,    29,    30,    -1,
    23,    33,    34,    35,    36,    37,    38,    30,    -1,    -1,
    33,    34,    35,    36,    37,    38,    17,    16,    17,    18,
    19,    20,    23,    -1,    -1,    24,    -1,    -1,    -1,    30,
    -1,    -1,    33,    34,    35,    36,    -1,    38,    10,    11,
    12,    13,    14,    15,    16,    17,    18,    19,    20,    -1,
    -1,    -1,    24,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,    20,    -1,    21,    22,    -1,    21,    22,
    -1,    27,    -1,    29,    27,    -1,    29,    21,    22,    -1,
    21,    22,    -1,    27,    -1,    29,    27,    -1,    29,    16,
    17,    18,    19,    20
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 287 "prob.y"
{top = create_env(top,0);;
    break;}
case 2:
#line 287 "prob.y"
{
	if (e){
			printf("%s\nRejected \n%s \nCould not generate Three Address Code / Storage Layout\n",buffer,err);
			e=0;err[0]="\0";buffer[0]='\0';} 
 		else {	
			backpatch(yyvsp[-2].b->N,yyvsp[-1].addr); // for last statement
			printf("%s\nAccepted -> Three Address Code:\n",buffer);
			for (int i=0;i<code;i++){
				printf("%s",imcode[i]);
			}
			print_all_envs(top);
			
		}YYACCEPT;;
    break;}
case 3:
#line 300 "prob.y"
{YYACCEPT;;
    break;}
case 4:
#line 301 "prob.y"
{e=1;strcpy(err,"Invalid Statements");
		printf("%s \nRejected -> %s \nCould not generate Three Address Code / Storage Layout\n",buffer,err);
		YYACCEPT; // stop the parsing
		;
    break;}
case 5:
#line 307 "prob.y"
{if (!e){yyval.b = yyvsp[-1].b;};
    break;}
case 6:
#line 308 "prob.y"
{if (!e){backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
										yyval.b = createBoolNode();
										yyval.b->N = merge(yyvsp[-3].b->F,yyvsp[0].b->N);
										};
    break;}
case 7:
#line 312 "prob.y"
{if (!e){
		backpatch(yyvsp[-7].b->T,yyvsp[-5].addr);
		backpatch(yyvsp[-7].b->F,yyvsp[-1].addr);
		yyval.b = createBoolNode();
		yyval.b->N = merge(merge(yyvsp[-4].b->N,yyvsp[-2].b->N),yyvsp[0].b);
	};
    break;}
case 8:
#line 319 "prob.y"
{if (!e){strcpy(err,"missing (");yyerrok;e=1;}
					printf("%s \nRejected -> %s -> Could not generate Three Address Code / Storage Layout\n",buffer,err);
					YYACCEPT; // stop the parsing or else loop
					;
    break;}
case 9:
#line 324 "prob.y"
{if (!e){
		backpatch(yyvsp[0].b->N,yyvsp[-5].addr);
		backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
		yyval.b = createBoolNode();
		yyval.b->N = yyvsp[-3].b->F;
		sprintf(imcode[code],"%d goto %d\n",code,yyvsp[-5].addr);
		code++;
		};
    break;}
case 10:
#line 332 "prob.y"
{top = create_env(top,offset);offset=0;;
    break;}
case 11:
#line 332 "prob.y"
{if (!e) {
						yyval.b = createBoolNode();
						yyval.b->N = yyvsp[-1].b->N;
						top = top->prev;
						if (!top) offset =0;
						else offset = top->prev_offset;
						};
    break;}
case 12:
#line 339 "prob.y"
{if (!e){yyval.b=createBoolNode();};
    break;}
case 13:
#line 340 "prob.y"
{if (!e) {yyval.b=createBoolNode();};
    break;}
case 14:
#line 341 "prob.y"
{if (!e) 	{strcpy(err,"; missing");yyerrok;e=1;}
							printf("%s\nRejected -> %s -> Could not generate Three Address Code / Storage Layout\n",buffer,err);
							YYACCEPT; // stop the parsing
							;
    break;}
case 15:
#line 345 "prob.y"
{if (!e){yyval.b=createBoolNode();};
    break;}
case 16:
#line 347 "prob.y"
{
	struct Decl* temp = yyvsp[-1].decl;
	while(temp){
		if (temp->re){
			e=1;
			Symbol* s = get(top->table,temp->key);
			if (strcmp(s->type,yyvsp[-2].type->str)==0){
				sprintf(err+strlen(err),"Redeclaration of %s\n",s->name);
			}
			else{
				sprintf(err+strlen(err),"conflicting types for %s\n",s->name);
			}
		}
		if (strcmp(temp->type,"")==0){
			Symbol* s = get(top->table,temp->key);
			s->offset = offset;
			offset+=yyvsp[-2].type->size;
			strcpy(s->type,yyvsp[-2].type->str);
		}
		else{
			Symbol* s = get(top->table,temp->key);
			s->offset = offset;
			offset+=(temp->size*yyvsp[-2].type->size);
			strcpy(s->type,temp->type);
			sprintf(s->type+strlen(s->type),"%s %d",yyvsp[-2].type,temp->size*yyvsp[-2].type->size);
		}

		temp = temp->next;
	}
;
    break;}
case 17:
#line 378 "prob.y"
{if (get(top->table,yyvsp[-2].str)==NULL){
								Symbol* s = createSymbol(yyvsp[-2].str);
								put(top->table,yyvsp[-2].str,s);
								yyval.decl = createDecl(yyvsp[-2].str);
								yyval.decl->next = yyvsp[0].decl;
							}
							else{
								yyval.decl = createDecl(yyvsp[-2].str);
								strcpy(yyval.decl->type,"");
								yyval.decl->re =1;
								}
						;
    break;}
case 18:
#line 390 "prob.y"
{
				if (get(top->table,yyvsp[-3].str)==NULL){
					Symbol* s = createSymbol(yyvsp[-3].str);
					put(top->table,yyvsp[-3].str,s);
					yyval.decl = createDecl(yyvsp[-3].str);
					yyval.decl->next = yyvsp[0].decl;
					strcpy(yyval.decl->type,yyvsp[-2].type->str);
					yyval.decl->size = yyvsp[-2].type->size;
				}
				else{
					yyval.decl = createDecl(yyvsp[-3].str);
					strcpy(yyval.decl->type,"");
					yyval.decl->re =1;
				}
	;
    break;}
case 19:
#line 405 "prob.y"
{if (get(top->table,yyvsp[0].str)==NULL){
						Symbol* s = createSymbol(yyvsp[0].str);
						put(top->table,yyvsp[0].str,s);
						yyval.decl = createDecl(yyvsp[0].str);
			}
			else{
						yyval.decl = createDecl(yyvsp[0].str);
						strcpy(yyval.decl->type,"");
						yyval.decl->re = 1;
						};
    break;}
case 20:
#line 415 "prob.y"
{sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].str,yyvsp[0].expr);code++;
					if (get(top->table,yyvsp[-2].str)==NULL){
						Symbol* s = createSymbol(yyvsp[-2].str);
						put(top->table,yyvsp[-2].str,s);
						yyval.decl = createDecl(yyvsp[-2].str);
						}
					else{
						yyval.decl = createDecl(yyvsp[-2].str);
						strcpy(yyval.decl->type,"");
						yyval.decl->re=1;
					};
    break;}
case 21:
#line 426 "prob.y"
{if (get(top->table,yyvsp[-1].str)==NULL){
						Symbol* s = createSymbol(yyvsp[-1].str);
						put(top->table,yyvsp[-1].str,s);
						yyval.decl = createDecl(yyvsp[-1].str);
						strcpy(yyval.decl->type,yyvsp[0].type->str);
						yyval.decl->size = yyvsp[0].type->size;
						}
					else{
						yyval.decl = createDecl(yyvsp[-1].str);
						strcpy(yyval.decl->type,"");
						yyval.decl->re=1;
					};
    break;}
case 22:
#line 439 "prob.y"
{yyval.type = createType();yyval.type->size=atoi(yyvsp[-1].str);sprintf(yyval.type->str,"array ");
					if (checkfloat(yyvsp[-1].str)){
						e=1;sprintf(err+strlen(err),"Array index cannot be float\n");
					};
    break;}
case 23:
#line 443 "prob.y"
{yyval.type = createType();yyval.type->size=yyvsp[0].type->size*atoi(yyvsp[-2].str);sprintf(yyval.type->str,"array %s",yyvsp[0].type->str);
						if (checkfloat(yyvsp[-2].str)){e=1;sprintf(err+strlen(err),"Array index cannot be float\n");
					};
    break;}
case 24:
#line 447 "prob.y"
{yyval.type = createType(); strcpy(yyval.type->str,yyvsp[0].str);yyval.type->size=4;;
    break;}
case 25:
#line 448 "prob.y"
{yyval.type = createType();strcpy(yyval.type->str,yyvsp[0].str);yyval.type->size=4;;
    break;}
case 26:
#line 449 "prob.y"
{yyval.type = createType();strcpy(yyval.type->str,yyvsp[0].str);yyval.type->size=1;;
    break;}
case 27:
#line 451 "prob.y"
{if (!e){backpatch(yyvsp[-2].b->N,yyvsp[-1].addr);
					yyval.b = createBoolNode();
					yyval.b->N = yyvsp[0].b->N;};
    break;}
case 28:
#line 454 "prob.y"
{if (!e){yyval.b = createBoolNode();
		yyval.b->N = yyvsp[-1].b->N;};
    break;}
case 29:
#line 458 "prob.y"
{strcpy(yyval.str,"=");;
    break;}
case 30:
#line 459 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 31:
#line 460 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 32:
#line 461 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 33:
#line 462 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 34:
#line 465 "prob.y"
{  if (!e){backpatch(yyvsp[-3].b->F,yyvsp[-1].addr);
							 	yyval.b = createBoolNode();	
								yyval.b->T = merge(yyvsp[-3].b->T,yyvsp[0].b->T);
								yyval.b->F = yyvsp[0].b->F;
							 };
    break;}
case 35:
#line 470 "prob.y"
{	if (!e){backpatch(yyvsp[-3].b->T,yyvsp[-1].addr);
								yyval.b = createBoolNode();
								yyval.b->T = yyvsp[0].b->T;
								yyval.b->F = merge(yyvsp[-3].b->F,yyvsp[0].b->F);
								};
    break;}
case 36:
#line 475 "prob.y"
{
		if (!e){
		yyval.b = createBoolNode();
		yyval.b->T = yyvsp[0].b->F;
		yyval.b->F = yyvsp[0].b->T;
		}
	;
    break;}
case 37:
#line 482 "prob.y"
{
		if (!e){
		yyval.b = createBoolNode();
		yyval.b->T = yyvsp[-1].b->T;
		yyval.b->F = yyvsp[-1].b->F;
		}
	;
    break;}
case 38:
#line 489 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);
							code++;
							};
    break;}
case 39:
#line 497 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 40:
#line 503 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 41:
#line 509 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 42:
#line 515 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 43:
#line 521 "prob.y"
{if(!e) {sprintf(imcode[code],"%d if %s %s %s goto ",code,yyvsp[-2].expr->str,yyvsp[-1].str,yyvsp[0].expr->str);
							yyval.b = createBoolNode();
							yyval.b->T = createNode(code);
							code++;
							sprintf(imcode[code],"%d goto ",code);
							yyval.b->F = createNode(code);code++;};
    break;}
case 44:
#line 527 "prob.y"
{if (!e){
		yyval.b = createBoolNode();
		yyval.b->T = createNode(code);
		sprintf(imcode[code],"%d goto ",code);
		code++;
	};
    break;}
case 45:
#line 534 "prob.y"
{if (!e){
		yyval.b = createBoolNode();
		yyval.b->F = createNode(code);
		sprintf(imcode[code],"%d goto ",code);
		code++;
	};
    break;}
case 46:
#line 541 "prob.y"
{yyval.addr=code;;
    break;}
case 47:
#line 542 "prob.y"
{yyval.b=createBoolNode();
	yyval.b->N = createNode(code);
	sprintf(imcode[code],"%d goto ",code);
	code++;
	;
    break;}
case 48:
#line 548 "prob.y"
{if (!e && yyvsp[-2].expr->lv){
							char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");
							checkTypeAssign(yyvsp[-2].expr,yyvsp[0].expr,ct1);
							if(strcmp(ct1,"")){
								strcpy(yyvsp[0].expr->str,ct1);
							}
							if (strlen(yyvsp[-1].str)==1){sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].expr,yyvsp[0].expr);code++;}
							else{
								char* t = genvar();
								sprintf(imcode[code],"%d %s = %s %c %s\n",code,t,yyvsp[-2].expr,yyvsp[-1].str[0],yyvsp[0].expr);code++;
								sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].expr,t);code++;
								
							}
							yyval.b = createBoolNode();
							}
							if (!yyvsp[-2].expr->lv){e=1;strcpy(err,"L value not assignable");};
    break;}
case 49:
#line 565 "prob.y"
{if (!e){yyval.expr = createExpr();char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");char* ct2 = (char*)malloc(sizeof(char));strcpy(ct2,"");checkType(yyvsp[-2].expr,yyvsp[0].expr,ct1,ct2,yyval.expr->type);if(strcmp(ct1,"")){strcpy(yyvsp[-2].expr->str,ct1);}if(strcmp(ct2,"")){strcpy(yyvsp[0].expr->str,ct2);}char* t = genvar();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s + %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 50:
#line 566 "prob.y"
{if (!e){yyval.expr = createExpr();char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");char* ct2 = (char*)malloc(sizeof(char));strcpy(ct2,"");checkType(yyvsp[-2].expr,yyvsp[0].expr,ct1,ct2,yyval.expr->type);if(strcmp(ct1,"")){strcpy(yyvsp[-2].expr->str,ct1);}if(strcmp(ct2,"")){strcpy(yyvsp[0].expr->str,ct2);}char* t = genvar();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s - %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 51:
#line 567 "prob.y"
{if (!e){yyval.expr = createExpr();char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");char* ct2 = (char*)malloc(sizeof(char));strcpy(ct2,"");checkType(yyvsp[-2].expr,yyvsp[0].expr,ct1,ct2,yyval.expr->type);if(strcmp(ct1,"")){strcpy(yyvsp[-2].expr->str,ct1);}if(strcmp(ct2,"")){strcpy(yyvsp[0].expr->str,ct2);}char* t = genvar();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s * %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 52:
#line 568 "prob.y"
{if (!e){yyval.expr = createExpr();char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");char* ct2 = (char*)malloc(sizeof(char));strcpy(ct2,"");checkType(yyvsp[-2].expr,yyvsp[0].expr,ct1,ct2,yyval.expr->type);if(strcmp(ct1,"")){strcpy(yyvsp[-2].expr->str,ct1);}if(strcmp(ct2,"")){strcpy(yyvsp[0].expr->str,ct2);}char* t = genvar();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s / %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 53:
#line 569 "prob.y"
{if (!e){if (strcmp(yyvsp[0].expr->type,"float")==0 || strcmp(yyvsp[-2].expr->type,"float")==0){e=1;sprintf(err+strlen(err),"invalid operands to binary % (float)");}yyval.expr = createExpr();char* ct1 = (char*)malloc(sizeof(char));strcpy(ct1,"");char* ct2 = (char*)malloc(sizeof(char));strcpy(ct2,"");checkType(yyvsp[-2].expr,yyvsp[0].expr,ct1,ct2,yyval.expr->type);if(strcmp(ct1,"")){strcpy(yyvsp[-2].expr->str,ct1);}if(strcmp(ct2,"")){strcpy(yyvsp[0].expr->str,ct2);}char* t = genvar();strcpy(yyval.expr->str,t);sprintf(imcode[code],"%d %s = %s %% %s\n",code,t,yyvsp[-2].expr->str,yyvsp[0].expr->str);code++;yyval.expr->lv=0;};
    break;}
case 54:
#line 570 "prob.y"
{if (!e){strcpy(yyval.expr->str,yyvsp[-1].expr->str);};
    break;}
case 55:
#line 572 "prob.y"
{e=1;strcpy(err,"Missing operand");yyerrok;;
    break;}
case 56:
#line 573 "prob.y"
{yyval.expr = yyvsp[0].expr;
    break;}
case 62:
#line 576 "prob.y"
{if (strcmp(yyvsp[-3].str,"-")){
							Env* temp = top;
							int found=0;
							while(temp){
								if (get(temp->table,yyvsp[-1].str)){
									found = 1;
									Symbol* t = get(temp->table,yyvsp[-1].str);
									strcpy(yyval.expr->type,t->type);
									break;
								}
								temp = temp->prev;
							}
							if (!found){
								sprintf(err+strlen(err),"%s is not declared in scope\n",yyvsp[-1].str);
								e=1;
							}
							char*t2=genvar();
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t2,yyvsp[-1].str,yyvsp[-2].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-1].str,t2);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t2);} 
					  else {
							if (!strcmp(yyvsp[-2].str,"--")){e=1;strcpy(err,"--- not allowed");}
							Env* temp = top;
							int found=0;
							while(temp){
								if (get(temp->table,yyvsp[-1].str)){
									found = 1;
									Symbol* t = get(temp->table,yyvsp[-1].str);
									strcpy(yyval.expr->type,t->type);
									break;
								}
								temp = temp->prev;
							}
							if (!found){
								sprintf(err+strlen(err),"%s is not declared in scope\n",yyvsp[-1].str);
								e=1;
							}
							else{
								char*t=genvar();char*t2=genvar();
								sprintf(imcode[code],"%s = %s %c 1\n%s = %s\n%s = - %s\n",t,yyvsp[-1].str,yyvsp[-2].str[0],yyvsp[-1].str,t,t2,t);
								yyval.expr = createExpr();
								strcpy(yyval.expr->str,t2);	
								}
							}
						yyval.expr->lv = 0;
					 ;
    break;}
case 63:
#line 623 "prob.y"
{if (strcmp(yyvsp[-3].str,"-")){char*t = genvar();char*t2=genvar();
							sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-2].str);code++;
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t2,yyvsp[-2].str,yyvsp[-1].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].str,t2);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t);
							Env* temp = top;
							int found=0;
							while(temp){
								if (get(temp->table,yyvsp[-2].str)){
									found = 1;
									Symbol* t = get(temp->table,yyvsp[-2].str);
									strcpy(yyval.expr->type,t->type);
									break;
								}
								temp = temp->prev;
							}
							if (!found){
								sprintf(err+strlen(err),"%s is not declared in scope\n",yyvsp[-2].str);
								e=1;
							}
							} 
					 	else{
							char* t = genvar();char* t1 = genvar();char *t3 = genvar();
							sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-2].str);code++;
							sprintf(imcode[code],"%d %s = %s %c 1\n",code,t1,yyvsp[-2].str,yyvsp[-1].str[0]);code++;
							sprintf(imcode[code],"%d %s = %s\n",code,yyvsp[-2].str,t1);code++;
							sprintf(imcode[code],"%d %s = -%s\n",code,t3,t);code++;
							yyval.expr = createExpr();
							strcpy(yyval.expr->str,t3);	
							Env* temp = top;
							int found=0;
							while(temp){
								if (get(temp->table,yyvsp[-2].str)){
									found = 1;
									Symbol* t = get(temp->table,yyvsp[-2].str);
									strcpy(yyval.expr->type,t->type);
									break;
								}
								temp = temp->prev;
							}
							if (!found){
								sprintf(err+strlen(err),"%s is not declared in scope\n",yyvsp[-2].str);
								e=1;
							}
						  	}
							yyval.expr->lv=0;;
    break;}
case 64:
#line 670 "prob.y"
{if (!strcmp(yyvsp[-2].str,"-")) {char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);
										sprintf(imcode[code],"%d %s = - %s\n",code,t,yyvsp[-1].str);
										code++;} 
				else{char* t = genvar();yyval.expr = createExpr();
					yyval.expr = createExpr();
					strcpy(yyval.expr->str,t);
					sprintf(imcode[code],"%d %s = %s\n",code,t,yyvsp[-1].str);code++;
				}
				if (checkfloat(yyvsp[-1].str)){
					strcpy(yyval.expr->type,"float");
				}
				else{
					strcpy(yyval.expr->type,"int");
				}
				yyval.expr->lv = 0;;
    break;}
case 65:
#line 685 "prob.y"
{if (!strcmp(yyvsp[-2].str,"-")) {char* t = genvar();yyval.expr = createExpr();strcpy(yyval.expr->str,t);
										sprintf(imcode[code],"%d %s = - %s\n",code,t,yyvsp[-1].str);
										code++;yyval.expr->lv=0;} 
				 else{yyval.expr = createExpr();strcpy(yyval.expr,yyvsp[-1].str);
						yyval.expr->lv=1;}
				Env* temp = top;
				int found=0;
				while(temp){
					if (get(temp->table,yyvsp[-1].str)){
						found = 1;
						Symbol* t = get(temp->table,yyvsp[-1].str);
						strcpy(yyval.expr->type,t->type);
						break;
					}
					temp = temp->prev;
				}
				if (!found){
					sprintf(err+strlen(err),"%s is not declared in scope\n",yyvsp[-1].str);
					e=1;
							};
    break;}
case 66:
#line 705 "prob.y"
{e=1;strcpy(err,"cannot increment a constant value");;
    break;}
case 67:
#line 706 "prob.y"
{e=1;strcpy(err,"cannot decrement a constant value");;
    break;}
case 68:
#line 707 "prob.y"
{e=1;strcpy(err,"cannot increment a constant value");;
    break;}
case 69:
#line 708 "prob.y"
{e=1;strcpy(err,"cannot decrement a constant value");;
    break;}
case 70:
#line 710 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 71:
#line 710 "prob.y"
{strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 72:
#line 712 "prob.y"
{e=1;strcpy(err,"expression is not assignable");;
    break;}
case 73:
#line 713 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 74:
#line 714 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 76:
#line 716 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 77:
#line 717 "prob.y"
{e=1;strcpy(err,"missing operator");;
    break;}
case 79:
#line 719 "prob.y"
{strcpy(yyval.str,"-");;
    break;}
case 80:
#line 719 "prob.y"
{strcpy(yyval.str,"");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 721 "prob.y"


char* genvar(){
	char *re = (char*)malloc(sizeof(char)*100);
    sprintf(re,"t%d",label);
    label++;
    return re;
}

int yyerror(char* msg){
	/* printf("%s\nRejected -> Invalid Statement -> Could not generate Three Address Code\n",buffer); */
	return 0;
}

int main(int argc,char* argv[]){
	/* yydebug=1; */
	yyin = fopen(argv[1],"r");
	yyparse();
	return 0;
}


